# The following three options taken from
# https://www.dolthub.com/blog/2022-03-18-migrating-to-yarn-2/#a-performance-improvement-for-yarn-2-without-zero-installs
#
# Instructs Yarn to not compress the zip files in the cache. For zero-installs
# size of cache is a concern, for nm installs it is not, because you don't put
# it into Git, so you can reduce load on your CPU by disabling compression.
compressionLevel: 0

enableColors: true

enableGlobalCache: false

# If true, Yarn will print any patch sections (hunks) that could not be applied
# successfully to the terminal.
enableInlineHunks: true

injectEnvironmentFiles:
  # Although this is "supposed" to be the default, if you run yarn inside a
  # workspace it won't load the .env.yarn file. See
  # https://github.com/yarnpkg/berry/issues/6111
  - ".env.yarn?"

# Instructs Yarn to use hardlinks when it has to create duplicates packages in
# the node_modules. It reduces the total size of node_modules on disk.
nmMode: hardlinks-local

nodeLinker: node-modules

preferReuse: true

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - musl
    - glibc

